Lab4/Models/Community.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lab4.Models
{
    public class Community
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Registration Number")]
        [Required]
        public string Id { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Budget { get; set; }

        //A collection of  navigation propertys
        public ICollection<CommunityMembership> Membership { get; set; }
        public ICollection<Advertisement> Advertisements { get; set; }
    }
}

Lab4/Models/ViewModels/CommunityViewModel.cs
using System.Collections.Generic;

namespace Lab4.Models.ViewModels
{
    public class CommunityViewModel
    {
        public IEnumerable<Student> Students { get; set; }
        public IEnumerable<Community> Communities { get; set; }
        public IEnumerable<CommunityMembership> CommunityMemberships { get; set; }
    }
}

Lab4/Controllers/AdvertisementController.cs
using Azure;
using Azure.Storage.Blobs;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly SchoolCommunityContext _context;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly string containerName = "images";
        public AdvertisementController(SchoolCommunityContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }

        public async Task<IActionResult> IndexAsync(string id)
        {
            var viewModel = new AdsViewModel();
            viewModel.Community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.Advertisements = await _context.Advertisements.Where(x => x.community.Id == id).ToListAsync();
            return View(viewModel);
        }
        public IActionResult Upload(string id)
        {
            var viewModel = new FileInputViewModel();
            Community community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.CommunityId = community.Id;
            viewModel.CommunityTitle = community.Title;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadFile(IFormFile file, string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlobContainerClient containerClient;
            // Create the container and return a container client object
            try
            {
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(containerName);
                // Give access to public
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            }
            catch (RequestFailedException)
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }


            try
            {
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(file.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await file.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }

                // add the photo to the database if it uploaded successfully
                var image = new Advertisement();
                image.Url = blockBlob.Uri.AbsoluteUri;
                image.FileName = file.FileName;
                image.community = _context.Communities.Where(i => i.Id == id).Single();
                _context.Advertisements.Add(image);
                _context.SaveChanges();
            }
            catch (RequestFailedException)
            {
                View("Error");
            }

            return RedirectToAction("Index", new { id = id });
        }

        public IActionResult Delete(string communityId, int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = _context.Communities.Where(x => x.Id == communityId).Single();
            var viewModel = new FileInputViewModel();
            viewModel.CommunityId = community.Id;
            viewModel.CommunityTitle = community.Title;
            viewModel.Advertisement = _context.Advertisements.Where(m => m.AdvertisementId == id).Single();
            if (viewModel.Advertisement == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

       [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string communityId, int id)
        {



            var image = await _context.Advertisements.FindAsync(id);


            BlobContainerClient containerClient;
            // Get the container and return a container client object
            try
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            try
            {
                // Get the blob that holds the data
                var blockBlob = containerClient.GetBlobClient(image.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                _context.Advertisements.Remove(image);
                await _context.SaveChangesAsync();

            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            return RedirectToAction("Index", new { id = communityId });
        }
    }
}

Lab4/Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;

namespace Lab4.Controllers
{
    public class CommunityController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public CommunityController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Community
        public async Task<IActionResult> Index(string Id)
        {
            var viewModel = new CommunityViewModel();
            viewModel.Communities = await _context.Communities
                  .Include(i => i.Membership)
                  .ThenInclude(i => i.Student)
                  .AsNoTracking()
                  .OrderBy(i => i.Title)
                  .ToListAsync();

            if (Id != null)
            {
                ViewData["CommunityID"] = Id;
                viewModel.CommunityMemberships = viewModel.Communities.Where(
                    x => x.Id == Id).Single().Membership;
            }
            return View(viewModel);
        }

        // GET: Community/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // GET: Community/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Community/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Budget")] Community community)
        {
            if (ModelState.IsValid)
            {
                _context.Add(community);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities.FindAsync(id);
            if (community == null)
            {
                return NotFound();
            }
            return View(community);
        }

        // POST: Community/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Budget")] Community community)
        {
            if (id != community.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(community);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommunityExists(community.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var viewModel = new AdsViewModel();
            viewModel.Community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.Advertisements = await _context.Advertisements.Where(x => x.community.Id == id).ToListAsync();
            return View(viewModel);
        }

        // POST: Community/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var community = await _context.Communities.FindAsync(id);
            _context.Communities.Remove(community);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommunityExists(string id)
        {
            return _context.Communities.Any(e => e.Id == id);
        }
    }
}

Lab4/Views/Community/Create.cshtml
@model Lab4.Models.Community

@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}

<h1 class="title">Create</h1>
<br />
<h1 class="subtitle">Community</h1>
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="field">
        <label asp-for="Id" class="label"></label>
        <div class="control">
            <input asp-for="Id" class="input" type="text" placeholder="Last Name" />
        </div>
        <span asp-validation-for="Id" class="has-text-danger"></span>
    </div>
    <div class="field">
        <label asp-for="Title" class="label"></label>
        <div class="control">
            <input asp-for="Title" class="input" type="text" placeholder="Last Name" />
        </div>
        <span asp-validation-for="Title" class="has-text-danger"></span>
    </div>
    <div class="field">
        <label asp-for="Budget" class="label"></label>
        <div class="control">
            <input asp-for="Budget" class="input" type="text" placeholder="Last Name" />
        </div>
        <span asp-validation-for="Budget" class="has-text-danger"></span>
    </div>
    <div class="field is-grouped">
        <div class="control">
            <input type="submit" value="Create" class="button is-link" />
        </div>
        <div class="control">
            <a asp-action="Index" class="button is-link is-light">Back to List</a>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab4/Views/Community/Delete.cshtml
@model Lab4.Models.ViewModels.AdsViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Delete";
}

<h1 class="title">Delete</h1>
<br />
<h1 class="subtitle">Community</h1>
<hr />
<table class="table is-narrow is-hoverable">
    <tbody>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Community.Title)</td>
            <td>@Html.DisplayFor(model => model.Community.Title)</td>
        </tr>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Community.Budget)</td>
            <td>@Html.DisplayFor(model => model.Community.Budget)</td>
        </tr>
    </tbody>
</table>
@if (Model.Advertisements.Count() == 0)
{
    <h1 class="subtitle">Are you sure you want to delete this?</h1>
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Community.Id" />
        <input class="button is-link" type="submit" value="Delete" /> &nbsp;
        <a class="button is-link is-light" asp-action="Index">Back to List</a>
    </form>
}
else
{
    <p>You cannot delete a community until all associated advertisements are deleted.</p>
    <br />
    <a class="button is-link is-light" asp-action="Index">Back to List</a>
}

Lab4/Views/Community/Details.cshtml
@model Lab4.Models.Community

@{
    Layout = "_Layout";
    ViewData["Title"] = "Details";
}

<h1 class="title">Details</h1>
<br />
<h1 class="subtitle">Community</h1>
<hr />
<table class="table is-narrow is-hoverable">
    <tbody>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Title)</td>
            <td>@Html.DisplayFor(model => model.Title)</td>
        </tr>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Budget)</td>
            <td>@Html.DisplayFor(model => model.Budget)</td>
        </tr>
    </tbody>
</table>
<div>
    <a class="button is-link" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> &nbsp;
    <a class="button is-link is-light" asp-action="Index">Back to List</a>
</div>

Lab4/Views/Community/Edit.cshtml
@model Lab4.Models.Community

@{
    Layout = "_Layout";
    ViewData["Title"] = "Edit";
}

<h1 class="title">Edit</h1>
<br />
<h1 class="subtitle">Community</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="field">
                <label asp-for="Title" class="label"></label>
                <div class="control">
                    <input asp-for="Title" class="input" type="text" placeholder="Title" />
                </div>
                <span asp-validation-for="Title" class="has-text-danger"></span>
            </div>
            <div class="field">
                <label asp-for="Budget" class="label"></label>
                <div class="control">
                    <input asp-for="Budget" class="input" type="text" placeholder="Budget" />
                </div>
                <span asp-validation-for="Budget" class="has-text-danger"></span>
            </div>
            <div class="field is-grouped">
                <div class="control">
                    <input type="submit" value="Save" class="button is-link" />
                </div>
                <div class="control">
                    <a asp-action="Index" class="button is-link is-light">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab4/Views/Community/Index.cshtml
@model Lab4.Models.ViewModels.CommunityViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}

<h1 class="title">Index</h1>
<br />
<a class="button is-link" asp-action="Create">Create New</a>
<hr />
<table class="table is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Budget
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Communities)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Budget)
                </td>
                <td>
                    <a class="button is-link" asp-action="Index" asp-route-id="@item.Id">Select</a> &nbsp;
                    <a class="button is-link" asp-controller="Advertisement" asp-action="Index" asp-route-id="@item.Id">Ads</a> &nbsp;
                    <a class="button is-link" asp-action="Edit" asp-route-id="@item.Id">Edit</a> &nbsp;
                    <a class="button is-link" asp-action="Details" asp-route-id="@item.Id">Details</a> &nbsp;
                    <a class="button is-link" asp-action="Delete" asp-route-id="@item.Id">Delete</a> &nbsp;
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.CommunityMemberships != null)
{
    <h3>
        Members of the community
    </h3>
    <table class="table">
        <tr>
            @if (Model.CommunityMemberships.Count() > 0)
            {
                <th> Name </th>
            }
            else
            {
                <th> No membership record exist </th>
            }
        </tr>
        @foreach (var item in Model.CommunityMemberships)
        {
            <tr>
                <td>@item.Student.FullName</td>
            </tr>
        }
    </table>
}