Lab4/Models/Advertisement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Models
{
    public class Advertisement
    {
        public int AdvertisementId { get; set; }

        [Required]
        [DisplayName("File Name")]
        public string FileName { get; set; }

        [Required]
        [Url]
        public string Url{ get; set; }

        [Required]
        public Community community { get; set; }
    }
}

Lab4/Controllers/AdvertisementController.cs
using Azure;
using Azure.Storage.Blobs;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly SchoolCommunityContext _context;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly string containerName = "images";
        public AdvertisementController(SchoolCommunityContext context, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _blobServiceClient = blobServiceClient;
        }

        public async Task<IActionResult> IndexAsync(string id)
        {
            var viewModel = new AdsViewModel();
            viewModel.Community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.Advertisements = await _context.Advertisements.Where(x => x.community.Id == id).ToListAsync();
            return View(viewModel);
        }
        public IActionResult Upload(string id)
        {
            var viewModel = new FileInputViewModel();
            Community community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.CommunityId = community.Id;
            viewModel.CommunityTitle = community.Title;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadFile(IFormFile file, string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            BlobContainerClient containerClient;
            // Create the container and return a container client object
            try
            {
                containerClient = await _blobServiceClient.CreateBlobContainerAsync(containerName);
                // Give access to public
                containerClient.SetAccessPolicy(Azure.Storage.Blobs.Models.PublicAccessType.BlobContainer);
            }
            catch (RequestFailedException)
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }


            try
            {
                // create the blob to hold the data
                var blockBlob = containerClient.GetBlobClient(file.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                using (var memoryStream = new MemoryStream())
                {
                    // copy the file data into memory
                    await file.CopyToAsync(memoryStream);

                    // navigate back to the beginning of the memory stream
                    memoryStream.Position = 0;

                    // send the file to the cloud
                    await blockBlob.UploadAsync(memoryStream);
                    memoryStream.Close();
                }

                // add the photo to the database if it uploaded successfully
                var image = new Advertisement();
                image.Url = blockBlob.Uri.AbsoluteUri;
                image.FileName = file.FileName;
                image.community = _context.Communities.Where(i => i.Id == id).Single();
                _context.Advertisements.Add(image);
                _context.SaveChanges();
            }
            catch (RequestFailedException)
            {
                View("Error");
            }

            return RedirectToAction("Index", new { id = id });
        }

        public IActionResult Delete(string communityId, int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = _context.Communities.Where(x => x.Id == communityId).Single();
            var viewModel = new FileInputViewModel();
            viewModel.CommunityId = community.Id;
            viewModel.CommunityTitle = community.Title;
            viewModel.Advertisement = _context.Advertisements.Where(m => m.AdvertisementId == id).Single();
            if (viewModel.Advertisement == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

       [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string communityId, int id)
        {



            var image = await _context.Advertisements.FindAsync(id);


            BlobContainerClient containerClient;
            // Get the container and return a container client object
            try
            {
                containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            try
            {
                // Get the blob that holds the data
                var blockBlob = containerClient.GetBlobClient(image.FileName);
                if (await blockBlob.ExistsAsync())
                {
                    await blockBlob.DeleteAsync();
                }

                _context.Advertisements.Remove(image);
                await _context.SaveChangesAsync();

            }
            catch (RequestFailedException)
            {
                return View("Error");
            }

            return RedirectToAction("Index", new { id = communityId });
        }
    }
}

Lab4/Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab4.Data;
using Lab4.Models;
using Lab4.Models.ViewModels;

namespace Lab4.Controllers
{
    public class CommunityController : Controller
    {
        private readonly SchoolCommunityContext _context;

        public CommunityController(SchoolCommunityContext context)
        {
            _context = context;
        }

        // GET: Community
        public async Task<IActionResult> Index(string Id)
        {
            var viewModel = new CommunityViewModel();
            viewModel.Communities = await _context.Communities
                  .Include(i => i.Membership)
                  .ThenInclude(i => i.Student)
                  .AsNoTracking()
                  .OrderBy(i => i.Title)
                  .ToListAsync();

            if (Id != null)
            {
                ViewData["CommunityID"] = Id;
                viewModel.CommunityMemberships = viewModel.Communities.Where(
                    x => x.Id == Id).Single().Membership;
            }
            return View(viewModel);
        }

        // GET: Community/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (community == null)
            {
                return NotFound();
            }

            return View(community);
        }

        // GET: Community/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Community/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Budget")] Community community)
        {
            if (ModelState.IsValid)
            {
                _context.Add(community);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var community = await _context.Communities.FindAsync(id);
            if (community == null)
            {
                return NotFound();
            }
            return View(community);
        }

        // POST: Community/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Budget")] Community community)
        {
            if (id != community.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(community);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommunityExists(community.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(community);
        }

        // GET: Community/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var viewModel = new AdsViewModel();
            viewModel.Community = _context.Communities.Where(x => x.Id == id).Single();
            viewModel.Advertisements = await _context.Advertisements.Where(x => x.community.Id == id).ToListAsync();
            return View(viewModel);
        }

        // POST: Community/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var community = await _context.Communities.FindAsync(id);
            _context.Communities.Remove(community);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommunityExists(string id)
        {
            return _context.Communities.Any(e => e.Id == id);
        }
    }
}

Lab4/Views/Advertisement/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Lab4.Models.ViewModels.FileInputViewModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Delete";
}

<h1 class="title">Delete add for community @Model.CommunityTitle</h1>


<table class="table is-narrow is-hoverable">
    <tbody>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Advertisement.FileName)</td>
            <td>@Html.DisplayFor(model => model.Advertisement.FileName)</td>
        </tr>
        <tr>
            <td class="has-text-weight-bold">@Html.DisplayNameFor(model => model.Advertisement.Url)</td>
            <td><img src="@Model.Advertisement.Url" style="max-width: 400px;" /></td>
        </tr>
    </tbody>
</table>

    <h1 class="subtitle">Are you sure you want to delete this?</h1>
    <form asp-action="Delete" asp-route-communityId="@Model.CommunityId">
        <input type="hidden" asp-for="@Model.Advertisement.FileName" />
        <input class="button is-link" type="submit" value="Delete"/> &nbsp;
        <a class="button is-link is-light" asp-action="Index" asp-route-id="@Model.CommunityId">Back to List</a>
    </form>
</div>

Lab4/Views/Advertisement/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Lab4.Models.ViewModels.AdsViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Index";
}
<h1 class="title">Show ads for community @Model.Community.Title</h1>
<div class="field is-grouped">
    <a class="button is-link" asp-action="Upload" asp-route-id="@Model.Community.Id">Upload New</a> &nbsp;
    <a class="button is-link is-light" asp-controller="Community" asp-action="Index">Back to list</a>
</div>
@if (Model.Advertisements.Count() == 0)
{
    <p>There are no files to display.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th class="has-text-weight-bold">
                    Advertisement ID
                </th>
                <th class="has-text-weight-bold">
                    Community ID
                </th>
                <th class="has-text-weight-bold"> 
                    File Name
                </th>
                <th class="has-text-weight-bold">
                    URL
                </th>
                <th class="has-text-weight-bold"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Advertisements)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AdvertisementId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.community.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    <img src="@item.Url" style="max-width: 400px;" />
                </td>
                <td>
                    <a class="button is-link" asp-action="Delete" asp-route-id="@item.AdvertisementId" asp-route-communityId="@item.community.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}

Lab4/Views/Advertisement/Upload.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Lab4.Models.ViewModels.FileInputViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Upload";
}

<h1 class="title">Upload</h1>
<br />
<h1 class="subtitle">Upload an add for community @Model.CommunityTitle</h1>
<hr />
<form asp-action="UploadFile" asp-route-id="@Model.CommunityId" enctype="multipart/form-data">
    <input name="file" type="file" accept="image/x-png,image/gif,image/jpeg" required>
    <br /><br />
    <div class="field is-grouped">
        <button name="upload" class="button is-link">Upload Now</button> &nbsp;
        <a class="button is-link is-light" asp-action="Index" asp-route-id="@Model.CommunityId">Back to List</a>
    </div>
</form>

<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}